class_name: "meddxagent.ddxdriver.patient_agents.llm_patient.LLMPatient"
config:
  
  # Model hyperparameters
  model:
    class_name: meddxagent.ddxdriver.models.llama31_8b.Llama318B  #["oai_azure_chat.OpenAIAzureChat", "oai_chat.OpenAIChat", "llama3_instruct.Llama3Instruct", "llama31_8b.Llama318B"]
    config:
      model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"  # ["gpt-4o", "llama31instruct", "meta-llama/Meta-Llama-3.1-8B-Instruct"]
