class_name: meddxagent.ddxdriver.rag_agents.miriad_rag.MiriadRAG

config:
  # Embedding Configuration
  embedding:
    model_names: ['BAAI/bge-large-en-v1.5','sentence-transformers/all-MiniLM-L6-v2']
    contents: ['qa'] #['qa', 'passage_text'] #'passage_text', 'qa', 'question'
    emb_model_name: 'BAAI/bge-large-en-v1.5' # 'sentence-transformers/all-MiniLM-L6-v2', 'BAAI/bge-large-en-v1.5'
    content: 'qa' #'passage_text', 'qa', 'question'


  # Model hyperparameters
  model:
    class_name: meddxagent.ddxdriver.models.llama31_8b.Llama318B   
    config:
      model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"  # ["gpt-4o", "llama31instruct", "meta-llama/Meta-Llama-3.1-8B-Instruct"]

  # Qdrant Configuration
  qdrant:
    host: 'localhost'
    port: 6333 # e.g., 6333 for Qdrant
    collection: 'miriad_{emb_model_name_short}_{content}'

  retrieval:
    top_k_search: 2
    max_keyword_searches: 3
